# Generated by Django 3.0.3 on 2020-03-31 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_housing'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='image',
            field=models.ImageField(default='', upload_to='housing_images'),
        ),
    ]
