# Generated by Django 3.0.3 on 2020-04-01 04:21

from django.db import migrations, models
import todos.models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_housing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='image',
            field=models.ImageField(default='', upload_to=todos.models.user_directory_path),
        ),
    ]
